version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: tests_nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    container_name: tests_wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    expose:
      - 9000
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    container_name: tests_mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wp_maria:/var/lib/mysql
    expose:
      - 3306

volumes:
  wp_data:
  wp_maria:
